name: Pipeline AWS

on:
  push:
    branches: [ "main" ]

jobs:
  ejecutar:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Instalar dependencias
      run: pip install boto3

    - name: Configurar credenciales AWS
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
      run: echo "Credenciales configuradas"

    - name: Ejecutar proyecto
      run: python main.py
